[OJT - 要素技術調査] csvファイルの読込/加工をするプログラムを作成しました
W-Nakayama-24/ojt_techSurvey pull request #1
Opened 2019-12-03 06:11 UTC by W-Nakayama-24

※
12月上～中旬に要素技術調査を終了し、最終課題へ入る予定です。
設計からテストまでをご覧頂いた前回のテーマと異なり、
今回は実装部分のみを短いスパンでご確認いただきたいと思います。

よろしくお願いします。

2019-12-03 07:35 UTC, skashiyama requested changes
そもそも世の中のcsvパーサーを使わなかった理由は何かあります?

2019-12-03 07:35 UTC, skashiyama commented on readCSV/CsvReader.java
> +    public String[][] readCsvWithoutComma(String path) throws FileNotFoundException, IOException {
withoutComma がよくわからないです。カンマなしのcsvファイルってことです?(そんなことないとおもいますが)
世の中にcsvのパーサーは転がっているので参考にして命名するといいでしょう

2019-12-03 07:45 UTC, W-Nakayama-24 commented on readCSV/CsvReader.java
> +    public String[][] readCsvWithoutComma(String path) throws FileNotFoundException, IOException {
>そもそも世の中のcsvパーサーを使わなかった理由は何かあります?

>withoutComma がよくわからないです。

すみません、説明が抜けていました。。。

csvリーダーの作成ではアルゴリズムを意識したプログラミングも併せて鍛える目的がありまして、
一般的なcsvパーサーと同様にカンマで区切る今回のタイプと
**区切った後のデータにカンマを含めるタイプ**の2種類を、できるだけ自力で作ってみるという課題内容になっています。

withOutCommaは区切った後のデータにカンマが含まれていないことから命名しましたが、
いま一度検討してみます。

2019-12-03 08:00 UTC, tmatsumura requested changes

2019-12-03 08:00 UTC, tmatsumura commented on readCSV/CsvReader.java
> +            return new String[0][0];
あまり詳しくないのですが、`new String[0][0]`というのは`null`のことなんですかね？こういう書き方をするのは何か理由があるのでしょうか？

2019-12-03 08:00 UTC, tmatsumura commented on readCSV/CsvReader.java
> +    public String[][] readCsvWithoutComma(String path) throws FileNotFoundException, IOException {
wihtoutCommaというのは違和感がありますね。カンマを外すというより、ファイルを読み込んで解析して各要素にアクセスしやすい形式にするという感じなのでparseとかがいい気がします（parseは1つの案なので、他の似たようなライブラリがどういう名前になっているか調べてみるといいと思います）

2019-12-04 00:27 UTC, W-Nakayama-24 commented on readCSV/CsvReader.java
> +            return new String[0][0];
以下のような意図で、データが取得できなかった場合 nullの代わりに空の配列を返却するようにしています。
- 呼び出し元のメソッドでnullチェックをする負担を無くすため
- 不意のNullPointerExceptionでプログラムが異常終了することを防ぐため

2019-12-04 00:56 UTC, W-Nakayama-24 commented on readCSV/CsvParser.java
> +    public String[][] convertTo2dArray(String path) throws FileNotFoundException, IOException {
命名の変更をしました。

ファイル名, クラス名 ： CsvReader ⇒ CsvParser
メソッド名： readWithOutComma ⇒ convertTo2dArray

2019-12-04 02:36 UTC, tmatsumura commented on readCSV/CsvReader.java
> +            return new String[0][0];
あ、すみません理解しました。空の2次元配列ですね。OKです

2019-12-04 07:22 UTC, tmatsumura approved these changes

2019-12-17 06:30 UTC, W-Nakayama-24 commented on readCSV/src/CsvParser2.java
> +     * それぞれ「データそのもの」か「データの区切り」かを解析する. 解析後,データ毎に分けてリスト(lineDataList)へ格納する.
誤：リスト(lineDataList)へ格納する.

訂：リスト(dataList)へ格納する.

2019-12-17 06:36 UTC, merged